databases:
  - name: dairy-farm-db
    databaseName: dairy_farm_db
    user: dairy_farm_user

services:
  - type: web
    name: dairy-farm-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn dairy_farm.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dairy-farm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: EMAIL_HOST_USER
        value: einsteinmokua100@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: "qeii jxyl rrjs alxv"
      - key: DEFAULT_FROM_EMAIL
        value: einsteinmokua100@gmail.com
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://localhost:3000,http://localhost:3000"
